#!/usr/bin/env python

import sys

from control_coding_challenge.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'control_coding_challenge'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
